# Generated by Django 2.2.7 on 2020-01-09 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szkody', '0002_auto_20191212_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klient',
            name='pracownik',
        ),
        migrations.AddField(
            model_name='klient',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
