# Generated by Django 2.2.7 on 2020-01-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('szkody', '0003_auto_20200109_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='imie',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nazwisko',
        ),
    ]
